### ISSUE TITLE
Number of filters in Progressive Growing of GANs implementation

### ISSUE THREAD

**Issue by jonathanyin12** [Mylittlerapture/GANLib#1]
I noticed that in your implementation, you set the number of filters in every convolutional layer as 64.

Have you tried to vary the number of filters like they do in the original paper? 

I attempted this but I found that the layer weight shape for new resolutions become incompatible with the weight shape saved from previous resolutions due to the number of filters changing. Any potential solution or work around to this problem?

Thanks.

**Comment by Mylittlerapture** [comment]
It definitely possible to do, just by creating list of number of filters and applying them according to grow step. But you should notice that in this case you should have two convolution layer on each layer of grow, like in the original paper to preserve compatibility of shapes. At least on the discriminator side. It quickly became quite expensive though, so I stick to simpler solution with one constant number of filters.

**Comment by jonathanyin12** [comment]
I am not sure how having two convolution layers would preserve shape compatibility since the number of filters is changing. Perhaps my understanding is flawed, but here is what happens when I tried a list of filters with two convolution layers for each increase in resolution.

Suppose image_size_list = [4, 8, 16, 32] and filters_list = [128, 128, 128, 64].

During resolutions 4, 8, and 16, the weights associated with the 'to_rgb' layer are of shape (1, 1, 128, 3) since the preceding convolution layer's output shape is (128, 16, 16). However, when the resolution increases to size 32, the preceding convolution layer's output shape becomes (64, 32, 32). Thus, the expected weight shape for the 'to_rgb' layer is (1, 1, 64, 3). This is problematic because the previous weight shape that is saved for the 'to_rgb' layer is (1, 1, 128, 3).

**Comment by Mylittlerapture** [comment]
I got you now. The thing is, you actually not supposed to clone your 'to_rgb' weights to new 'to_rgb' layer. I did it to speed up training process. I just updated pg_gan.py example with list of filters to better match original paper and avoid this misleading part.

**Comment by jonathanyin12** [comment]
Thanks! That makes a lot more sense.
On a side note, I really appreciate your Keras GAN library. It has helped me in my ML endeavors. I hope you keep working on it!
